default_language_version:
  python: python3

fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(setup\.cfg)
      - id: end-of-file-fixer
        exclude: ^(setup\.cfg)
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: false
        exclude: ^(docs/|setup\.py)

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
